# Generated by Django 5.2.5 on 2026-02-12 15:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del establecimiento')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('porcentaje_cashback', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Porcentaje de cashback (%)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Establecimiento',
                'verbose_name_plural': 'Establecimientos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_registro', models.DateField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=19, unique=True, verbose_name='Número de tarjeta')),
                ('tipo', models.CharField(choices=[('VISA', 'Visa'), ('MASTERCARD', 'MasterCard'), ('AMEX', 'American Express'), ('OTRO', 'Otro')], default='VISA', max_length=20, verbose_name='Tipo de tarjeta')),
                ('banco', models.CharField(max_length=100, verbose_name='Nombre del banco')),
                ('fecha_vencimiento_pago', models.IntegerField(default=15, help_text='Día del mes (1-31) para el pago')),
                ('fecha_vencimiento_tarjeta', models.DateField(blank=True, default=datetime.date(2029, 2, 11), help_text='Formato: MM/AA (Ej: 12/25 para Diciembre 2025)', null=True, verbose_name='Fecha de vencimiento de la tarjeta (MM/AA)')),
                ('limite_credito', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Límite de crédito')),
                ('saldo_actual', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo actual')),
                ('activa', models.BooleanField(default=True, verbose_name='Tarjeta activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('titular', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas_titular', to='tarjetas_app.persona', verbose_name='Titular principal')),
                ('usuarios', models.ManyToManyField(to='tarjetas_app.persona', verbose_name='Personas que la usan')),
            ],
            options={
                'verbose_name': 'Tarjeta',
                'verbose_name_plural': 'Tarjetas',
                'ordering': ['banco', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('COMPRA', 'Compra'), ('PAGO', 'Pago'), ('COMISION', 'Comisión'), ('INTERES', 'Interés'), ('CASHBACK', 'Cashback')], max_length=10, verbose_name='Tipo de movimiento')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('monto_cashback', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cashback generado')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha', models.DateField(verbose_name='Fecha del movimiento')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('establecimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tarjetas_app.establecimiento', verbose_name='Establecimiento')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='tarjetas_app.persona', verbose_name='Persona')),
                ('tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='tarjetas_app.tarjeta', verbose_name='Tarjeta')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'ordering': ['-fecha', '-fecha_registro'],
            },
        ),
    ]
