# Generated by Django 5.2.11 on 2026-02-17 17:15

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas_app', '0002_crear_superusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='compra_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='tarjetas_app.movimiento', verbose_name='Compra que paga'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='fecha_vencimiento_tarjeta',
            field=models.DateField(blank=True, default=datetime.date(2029, 2, 16), help_text='Formato: MM/AA (Ej: 12/25 para Diciembre 2025)', null=True, verbose_name='Fecha de vencimiento de la tarjeta (MM/AA)'),
        ),
    ]
