# Generated by Django 5.2.11 on 2026-02-18 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas_app', '0004_alter_tarjeta_fecha_vencimiento_tarjeta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='compra_origen',
        ),
        migrations.CreateModel(
            name='PagoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_aplicado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_recibidos', to='tarjetas_app.movimiento')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_a_compras', to='tarjetas_app.movimiento')),
            ],
            options={
                'verbose_name': 'Pago aplicado a compra',
                'verbose_name_plural': 'Pagos aplicados a compras',
                'unique_together': {('pago', 'compra')},
            },
        ),
    ]
