# Generated by Django 5.2.11 on 2026-02-25 22:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas_app', '0005_remove_movimiento_compra_origen_pagocompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='es_a_meses',
            field=models.BooleanField(default=False, verbose_name='Compra a meses'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='meses_pagados',
            field=models.IntegerField(default=0, verbose_name='Meses pagados'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='monto_mensual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto por mes'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='numero_meses',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de meses'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='fecha_vencimiento_tarjeta',
            field=models.DateField(blank=True, default=datetime.date(2029, 2, 24), help_text='Formato: MM/AA (Ej: 12/25 para Diciembre 2025)', null=True, verbose_name='Fecha de vencimiento de la tarjeta (MM/AA)'),
        ),
        migrations.CreateModel(
            name='LiberacionMensualidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_mes', models.IntegerField(help_text='Número de mes (1,2,3...)')),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liberaciones', to='tarjetas_app.movimiento')),
            ],
        ),
    ]
