# Generated by Django 5.2.11 on 2026-02-26 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas_app', '0006_movimiento_es_a_meses_movimiento_meses_pagados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='tipo',
            field=models.CharField(choices=[('COMPRA', 'Compra'), ('PAGO', 'Pago'), ('COMISION', 'Comisión'), ('INTERES', 'Interés'), ('MENSUALIDAD', 'Mensualidad de compra a meses'), ('CASHBACK', 'Cashback')], max_length=15, verbose_name='Tipo de movimiento'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='fecha_vencimiento_tarjeta',
            field=models.DateField(blank=True, default=datetime.date(2029, 2, 25), help_text='Formato: MM/AA (Ej: 12/25 para Diciembre 2025)', null=True, verbose_name='Fecha de vencimiento de la tarjeta (MM/AA)'),
        ),
    ]
