# Generated by Django 5.2.11 on 2026-03-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas_app', '0009_alter_tarjeta_fecha_vencimiento_tarjeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='fecha',
            field=models.DateField(db_index=True, verbose_name='Fecha del movimiento'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='tipo',
            field=models.CharField(choices=[('COMPRA', 'Compra'), ('PAGO', 'Pago'), ('COMISION', 'Comisión'), ('INTERES', 'Interés'), ('MENSUALIDAD', 'Mensualidad de compra a meses'), ('CASHBACK', 'Cashback')], db_index=True, max_length=15, verbose_name='Tipo de movimiento'),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['fecha'], name='tarjetas_ap_fecha_a52d2f_idx'),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['tipo'], name='tarjetas_ap_tipo_78134a_idx'),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['persona'], name='tarjetas_ap_persona_f0416a_idx'),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['tarjeta'], name='tarjetas_ap_tarjeta_9c66c8_idx'),
        ),
    ]
