# Generated by Django 5.2.11 on 2026-04-23 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas_app', '0010_alter_movimiento_fecha_alter_movimiento_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='fecha_vencimiento_tarjeta',
            field=models.DateField(blank=True, default=datetime.date(2029, 4, 22), help_text='Formato: MM/AA (Ej: 12/25 para Diciembre 2025)', null=True, verbose_name='Fecha de vencimiento de la tarjeta (MM/AA)'),
        ),
    ]
