# Generated by Django 5.2.11 on 2026-05-15 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas_app', '0012_alter_tarjeta_fecha_vencimiento_tarjeta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='fecha_vencimiento_tarjeta',
            field=models.DateField(blank=True, default=datetime.date(2029, 5, 14), help_text='Formato: MM/AA (Ej: 12/25 para Diciembre 2025)', null=True, verbose_name='Fecha de vencimiento de la tarjeta (MM/AA)'),
        ),
    ]
