# Generated by Django 5.2.11 on 2026-06-08 20:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas_app', '0013_alter_tarjeta_fecha_vencimiento_tarjeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta',
            name='dia_corte',
            field=models.IntegerField(default=15, help_text='Día del mes en que se genera el estado de cuenta (1-31)'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='fecha_vencimiento_tarjeta',
            field=models.DateField(blank=True, default=datetime.date(2029, 6, 7), help_text='Formato: MM/AA (Ej: 12/25 para Diciembre 2025)', null=True, verbose_name='Fecha de vencimiento de la tarjeta (MM/AA)'),
        ),
    ]
