# Generated by Django 5.2.11 on 2026-06-08 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas_app', '0014_tarjeta_dia_corte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta',
            name='es_principal',
            field=models.BooleanField(default=True, verbose_name='¿Es tarjeta principal?'),
        ),
    ]
